# Python Basics

Este notebook tiene por objetivo recordar los elementos básicos de operación con el lenguaje de programación Python.

## 0. Importa Las Librerías

In [3]:
import numpy as np
import pandas as pd

## 1. Tipos Primitivos

In [24]:
num1 = 20
num2 = 10.4
numi = 3 + 2j
char1 = 'a'

print("El tipo de num1 es: ",type(num1))
print("El tipo de num2 es: ",type(num2))
print("El tipo de numi es: ",type(numi))
print("El tipo de char1 es: ",type(char1))

El tipo de num1 es:  <class 'int'>
El tipo de num2 es:  <class 'float'>
El tipo de numi es:  <class 'complex'>
El tipo de char1 es:  <class 'str'>


## 2. Listas, Tuplas, Diccionarios Y Sets

Una lista y una tupla son lo mismo desde la perspectiva funcional, al final son objetos de diferente tipo, pero tienen el mismo objetivo, servir de contenedores de datos (no necesariamente del mismo tipo). Sintácticamente se diferencian en su creación por el uso de paréntesis (las tuplas) y los corchetes (las listas). Se accede a datos con índices numéricos.

La diferencia más determinante (hasta ahora aprendida) es que las tuplas son inmutables y las listas son mutables OJO!

Los diccionarios son como los "arreglos asociativos" es php, es decir, también son contenedores de datos (de tipo múltiple), pero en lugar de acceder a los datos mediantes indices numéricos, se accede mediante índices alfanuméricos. Se inicializa (define) con los caracteres "llaves" {}

Los sets (set), son colecciones de datos NO ORDENADOS, es decir, que no se accede a los datos con indices numéricos ni tampoco índices alfanuméricos, funcionan como colecciones de datos que aseguran la existencia de un solo valor en el conjunto de datos, por ejemplo, si se intenta generar un set con los siguientes datos

set_a = {7,-1,"Hola",0,'b',7,-4,0}

El objeto creado tendrá los siguientes elementos únicamente:

{7,-1,"Hola",0,'b',-4}

Por que los valores 7 y 0 en los datos de inicialización se encuentran repetidos, un objeto set se asegura de no tener datos repetidos.

In [25]:
# Las listas y las tuplas son lo más parecidos a los arreglos en php
tupla1 = (2,3,'Hola Mundo','SIBA','MMA',3.5,10,0,-0.5)
print("El tipo de tupla1 es: ",type(tupla1))

lista1 = [2,3,'Hola Mundo','SIBA','MMA',3.5,10,0,-0.5]
print("El tipo de lista1 es: ",type(lista1))

# Los diccionarios son lo más parecido a los arraglos asociativos en php
dic1 = {
    'a' : 'Primer valor',
    'b' : 'Segundo valor',
    'c' : 200,
    'd' : 34.23
}

print("El tipo de dic1 es: ",type(dic1))

# tomando porciones de las tuplas y listas
tupla1[0:2]

El tipo de tupla1 es:  <class 'tuple'>
El tipo de lista1 es:  <class 'list'>
El tipo de dic1 es:  <class 'dict'>


(2, 3)

In [26]:
#Accediendo a los datos en los diferentes tipos de datos
print('El segundo elemento de la Tupla: ',tupla1[1])
print('El tercer elemento de la Lista: ',lista1[2])
print('El elemento "a" del Diccionario es: ',dic1['a'])

El segundo elemento de la Tupla:  3
El tercer elemento de la Lista:  Hola Mundo
El elemento "a" del Diccionario es:  Primer valor


### 3. Cambiando tipos de datos (Casting)

In [27]:
a = 3.68
print ("El tipo de la variable a es float en este punto: ",type(a)) #Tipo de dato Float
a = int(a) #Casting a valor entero
print ("El tipo de la variable a es integer luego de realizar el cambio de tipo (casting): ",type(a))

El tipo de la variable a es float en este punto:  <class 'float'>
El tipo de la variable a es integer luego de realizar el cambio de tipo (casting):  <class 'int'>


In [28]:
5 + 4.99

9.99

In [29]:
12 * 0.55

6.6000000000000005

In [30]:
a = [2, 3,7, -1, 2, 0, -1, 8]

In [31]:
type(a)

list

In [32]:
vector1 = np.array(a)

In [33]:
type(vector1)

numpy.ndarray

In [34]:
vector1

array([ 2,  3,  7, -1,  2,  0, -1,  8])

In [35]:
vector1 + (2/4)

array([ 2.5,  3.5,  7.5, -0.5,  2.5,  0.5, -0.5,  8.5])

### 4. Ciclos en Python

In [36]:
# Usando una instrución for con una instrucción range()
for i in range(20):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [37]:
list2 = [2, 3, -1, 0, 4, -2, 9, 11, 4, -2, 5]
print("\n======================\n")

# Sin enumerate, es decir, ejecutando el elemento iterable directamente
for ele in list2:
    print("El item: ", ele,)

print("\n======================\n")

# Usando Enumerate para tomar el indice del objeto iterable
for i,ele in enumerate(list2):
    print("[Indice: ",i,"] El item: ", ele,) 



El item:  2
El item:  3
El item:  -1
El item:  0
El item:  4
El item:  -2
El item:  9
El item:  11
El item:  4
El item:  -2
El item:  5


[Indice:  0 ] El item:  2
[Indice:  1 ] El item:  3
[Indice:  2 ] El item:  -1
[Indice:  3 ] El item:  0
[Indice:  4 ] El item:  4
[Indice:  5 ] El item:  -2
[Indice:  6 ] El item:  9
[Indice:  7 ] El item:  11
[Indice:  8 ] El item:  4
[Indice:  9 ] El item:  -2
[Indice:  10 ] El item:  5


### 5. Funciones en Python

Para definir una función en python, se usa la palabra reservada: **def** 

In [38]:
def fnc1():
    #Cuerpo de la función
    return 1

def calc_square (base : int) -> float :
    square = base*base
    print("The square of %d is"%base,square)
    return square

In [39]:
#Operando las funciones
base = 3
cuadradoDe3 = calc_square(base)
print("El tipo de dato de calc_square(3) es",type(cuadradoDe3))
print("El valor retornado de la funcion fnc1() es... ", fnc1())
print("Calculando el cuadrado de %f que es:"%base,cuadradoDe3)

The square of 3 is 9
El tipo de dato de calc_square(3) es <class 'int'>
El valor retornado de la funcion fnc1() es...  1
Calculando el cuadrado de 3.000000 que es: 9


### Mención Especial Para Funciones Lambda

Las funciones Lambda son la forma de definición de función anónima en python cuando esta (la función), solo incluye una instrucción. La estructura de la definición de una función lambda es:

      Variable     Palabra   Parametros     Expresión
    contenedora   Reservada      |        (Instrucción)
        |             |          |              |
        |             |          |              |
        V             V          V              V
multiplicar_numeros = lambda  param1,param2: param1 * param2

Se usa invocando la función anónima almacenada en la variable contenedora así:

multiplicar_numeros (3,4) ***Retorna el número 12***

multiplicar_numeros (7,2) ***Retorna el número 14***

In [40]:
lambda_square = lambda x: x*x

print(lambda_square(2))
print(lambda_square(4))
print(lambda_square(7))

4
16
49


### 6. Clases y Objetos En Python

In [41]:
class Auto:
    ruedas = 4 # Variable de Clase
    def __init__(self,color,cc,tipo):
        self.color = color
        self.cc = cc
        self.tipo = tipo
    def getAutoInfo(self):
        return "Los datos del auto son los siguientes: \nColor: "+self.color+"\nCilindraje: "+str(self.cc)+"\nTipo: "+self.tipo+"\n"

auto_verde = Auto('Verde',1000,'Camioneta')
print(type(auto_verde))
print("El color del Auto es: %s"%auto_verde.color)
print("El cilindraje del Auto es: %d"%auto_verde.cc)
print("El tipo del Auto es: %s"%auto_verde.tipo)
print("La cantidad de ruedas en el Auto es: %s"%auto_verde.ruedas)
print("\n==========================================\n")
print(auto_verde.getAutoInfo())


Auto.ruedas = 6
auto_azul = Auto('Azul',1200,'Automovil')
print(type(auto_azul))
print("El color del Auto es: %s"%auto_azul.color)
print("El cilindraje del Auto es: %d"%auto_azul.cc)
print("El tipo del Auto es: %s"%auto_azul.tipo)
print("La cantidad de ruedas en el Auto es: %s"%auto_azul.ruedas)
print("\n==========================================\n")
print(auto_azul.getAutoInfo())

<class '__main__.Auto'>
El color del Auto es: Verde
El cilindraje del Auto es: 1000
El tipo del Auto es: Camioneta
La cantidad de ruedas en el Auto es: 4


Los datos del auto son los siguientes: 
Color: Verde
Cilindraje: 1000
Tipo: Camioneta

<class '__main__.Auto'>
El color del Auto es: Azul
El cilindraje del Auto es: 1200
El tipo del Auto es: Automovil
La cantidad de ruedas en el Auto es: 6


Los datos del auto son los siguientes: 
Color: Azul
Cilindraje: 1200
Tipo: Automovil



In [42]:
print(dir(auto_azul))
print(auto_azul.__dict__)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cc', 'color', 'getAutoInfo', 'ruedas', 'tipo']
{'color': 'Azul', 'cc': 1200, 'tipo': 'Automovil'}


### 7. Librería Numpy Para Manejo de Datos en Vectores, Marices o Tensores

El elemento fundamental de la librería Numpy son los objetos **Numpy Array**, que funcionalmente son similares a las listas nativas de Python, pero con una diferencia fundamental en la forma como se almacenan los datos.

En las listas de Python se pueden agregar elementos de cuqluier tipo de dato, de esta manera una lista en python puede contener elementos de tipo String, Integer, Float u otros objetos de otras clases (nativas o creadas por el usuario), el tipo de dato de cada elemento en este caso (las listas de python) se almacena en el elemento mismo de la lista, es decir, los elementos de una lista de python no solo almacenan el valor que contienen, sino que también almacenan el tipo dato, en contraste, los objetos **Numpy Array** solo almacenan elementos de un solo tipo de dato en el arreglo (Numpy Array) y el tipo de dato se almacena como un valor de cabecera del objeto **Numpy Array** de esta manera, se gana en eficiencia al momento de realizar operaciones sobre grandes volúmenes de datos, tales como: "element-wise" y ejecución en paralelo de tareas. 

In [43]:
nparray1 = np.array([1, 2, 3, 0, -2, 5, -2, 1, 0, 4])
nparray2 = np.array([4, 3, -1, 2, -7, 3, 1, 5, -3, 6])
print(type(nparray1))

#Operación element-wise
print(nparray1 * -2)
print(nparray1 * nparray2)

<class 'numpy.ndarray'>
[ -2  -4  -6   0   4 -10   4  -2   0  -8]
[ 4  6 -3  0 14 15 -2  5  0 24]


### 8. Librería Pandas - Series y DataFrames
 
Los elementos fundamentales de libreía Pandas son los objetos: **Series y DataFrame**, las series son arreglos de una sola dimensión con acceso a datos con indices numéricos, los DataFrames son arreglos bidimensionales con cabeceras. Son como una especie "hojas de cáculo", por lo menos en la forma como se distribuyen los datos en el DataFrame, cada columna en del dataframe puede ser tratada como un Serie de datos (tipo Serie).

Para inicializar una serie se pueden usar objetos nativos de python del tipo Tupla o Lista. Para inicializar un DataFrame se pueden utilizar o bien datos externos como archivos csv, json o excel, u objetos nativos de python Diccionarios. 

In [54]:
#Jugando con Series
pdserie_int = pd.Series([-2,3,5,9,10,-20,1,-3,0,-3,4,27]) #Definición de tipo automático, de acuerdo a los datos recibidos
pdserie_float = pd.Series([-2,3,5,9,10,-20,1,-3,0,-3,4,27],dtype=float) #Con definición de tipo de dato
print(pdserie_int)
print(type(pdserie_int))
print(pdserie_float)
print(type(pdserie_float))

0     -2
1      3
2      5
3      9
4     10
5    -20
6      1
7     -3
8      0
9     -3
10     4
11    27
dtype: int64
<class 'pandas.core.series.Series'>
0     -2.0
1      3.0
2      5.0
3      9.0
4     10.0
5    -20.0
6      1.0
7     -3.0
8      0.0
9     -3.0
10     4.0
11    27.0
dtype: float64
<class 'pandas.core.series.Series'>


In [59]:
#Jugando con DataFrames

#Cargando datos definidos en un Diccionario Python
dfFromMemory = pd.DataFrame({"Fecha":['2023-01-03','2023-01-07','2023-05-20','2023-10-29','2023-11-04'],"Temperatura Media":[20,21,22,28.4,27.1],"Lluvia":['si','so','si','no','no']})
print(dfFromMemory)
print(type(dfFromMemory))

        Fecha  Temperatura Media Lluvia
0  2023-01-03               20.0     si
1  2023-01-07               21.0     so
2  2023-05-20               22.0     si
3  2023-10-29               28.4     no
4  2023-11-04               27.1     no
<class 'pandas.core.frame.DataFrame'>


In [4]:
#Jugando con DataFrames

#Cargando datos desde un archivo csv
dfFromCsv = pd.read_csv('datos/datos-20231208.csv')
print(dfFromCsv)
print(type(dfFromCsv))

       Registros     Peso  Duración       Fecha                  Ini  \
0          10357  6138999       398  2023-11-13  2023-11-13 18:25:02   
1          11265  6692498       397  2023-07-17  2023-07-17 20:20:01   
2          11265  6692498       395  2023-07-17  2023-07-17 20:19:02   
3          11946  5405356       395  2023-12-05  2023-12-05 16:05:01   
4          11946  5405356       392  2023-12-05  2023-12-05 16:05:01   
...          ...      ...       ...         ...                  ...   
16094        235    49584         5  2023-12-04  2023-12-04 17:37:02   
16095        248    34906         4  2023-07-17  2023-07-17 19:26:01   
16096         96    41092         4  2023-07-31  2023-07-31 18:18:02   
16097        138    77152         3  2023-10-25  2023-10-25 20:06:02   
16098        117    19805         2  2023-11-21  2023-11-21 17:12:03   

                       Fin  
0      2023-11-13 19:21:23  
1      2023-07-17 21:02:39  
2      2023-07-17 21:10:36  
3      2023-12-05 1

In [73]:
print("========================================================================")
print("Uso de la función head del DataFrame, primeros 10 registros")
print("========================================================================")
dfFromCsv.head(10)

Uso de la función head del DataFrame, primeros 10 registros


Registros     Peso  Duración       Fecha                  Ini  \
0      10357  6138999       398  2023-11-13  2023-11-13 18:25:02   
1      11265  6692498       397  2023-07-17  2023-07-17 20:20:01   
2      11265  6692498       395  2023-07-17  2023-07-17 20:19:02   
3      11946  5405356       395  2023-12-05  2023-12-05 16:05:01   
4      11946  5405356       392  2023-12-05  2023-12-05 16:05:01   
5      10254  6075456       389  2023-11-14  2023-11-14 16:03:02   
6       3703  2863675       386  2023-08-08  2023-08-08 07:20:01   
7      11344  6752271       386  2023-08-15  2023-08-15 18:40:02   
8       3703  2863675       385  2023-08-08  2023-08-08 07:20:01   
9       3174  2057485       385  2023-08-15  2023-08-15 18:39:02   

                   Fin  
0  2023-11-13 19:21:23  
1  2023-07-17 21:02:39  
2  2023-07-17 21:10:36  
3  2023-12-05 17:24:37  
4  2023-12-05 17:20:34  
5  2023-11-14 17:04:30  
6  2023-08-08 08:22:28  
7  2023-08-15 19:43:48  
8  2023-08-08 08:26:31  
9  2023-08-15 20:44:22

In [71]:
print("========================================================================")
print("Uso de la función info del DataFrame")
print("========================================================================")
dfFromCsv.info()

Uso de la función info del DataFrame
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16099 entries, 0 to 16098
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Registros  16099 non-null  int64 
 1   Peso       16099 non-null  int64 
 2   Duración   16099 non-null  int64 
 3   Fecha      16099 non-null  object
 4   Ini        16099 non-null  object
 5   Fin        16099 non-null  object
dtypes: int64(3), object(3)
memory usage: 754.8+ KB


In [77]:
print("========================================================================")
print("Uso del atributo shape del DataFrame")
print("========================================================================")
dfFromCsv.shape

Uso de la función shape del DataFrame


(16099, 6)

In [78]:
print("========================================================================")
print("Uso de la función to_numpy del DataFrame")
print("========================================================================")
dfFromCsv.to_numpy()

Uso de la función to_numpy del DataFrame


array([[10357, 6138999, 398, '2023-11-13', '2023-11-13 18:25:02',
        '2023-11-13 19:21:23'],
       [11265, 6692498, 397, '2023-07-17', '2023-07-17 20:20:01',
        '2023-07-17 21:02:39'],
       [11265, 6692498, 395, '2023-07-17', '2023-07-17 20:19:02',
        '2023-07-17 21:10:36'],
       ...,
       [96, 41092, 4, '2023-07-31', '2023-07-31 18:18:02',
        '2023-07-31 18:24:14'],
       [138, 77152, 3, '2023-10-25', '2023-10-25 20:06:02',
        '2023-10-25 20:38:37'],
       [117, 19805, 2, '2023-11-21', '2023-11-21 17:12:03',
        '2023-11-21 18:42:48']], dtype=object)

In [13]:
print("========================================================================")
print("Uso de la función describe del DataFrame")
print("========================================================================")
dfFromCsv.describe()
#dfFromCsv.info()
#dfFromCsv.dtypes()


Uso de la función describe del DataFrame


Registros          Peso      Duración
count  16099.000000  1.609900e+04  16099.000000
mean    2042.964346  1.111980e+06     59.736505
std     1488.279610  9.656419e+05     49.365515
min       57.000000  1.980500e+04      2.000000
25%      972.000000  3.912220e+05     26.000000
50%     1565.000000  7.484650e+05     40.000000
75%     2883.000000  1.700513e+06     83.000000
max    13060.000000  7.712808e+06    398.000000

In [82]:
print("========================================================================")
print("Uso del atributo columns del DataFrame")
print("========================================================================")
dfFromCsv.columns

Uso del atributo columns del DataFrame


Index(['Registros', 'Peso', 'Duración', 'Fecha', 'Ini', 'Fin'], dtype='object')

In [85]:
print("========================================================================")
print("Uso de la función unique sobre una columna (Duración) del DataFrame")
print("========================================================================")
dfFromCsv['Duración'].unique()

Uso de la función unique sobre una columna (Duración) del DataFrame


array([398, 397, 395, 392, 389, 386, 385, 384, 380, 378, 375, 374, 369,
       367, 366, 364, 363, 361, 360, 359, 358, 355, 354, 352, 349, 346,
       344, 340, 339, 338, 337, 336, 334, 331, 329, 328, 327, 326, 325,
       323, 322, 321, 320, 318, 317, 314, 313, 311, 309, 308, 307, 305,
       304, 301, 297, 296, 295, 291, 290, 289, 286, 284, 280, 279, 278,
       275, 274, 272, 271, 269, 268, 266, 265, 264, 263, 261, 259, 258,
       257, 255, 254, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243,
       242, 241, 240, 239, 238, 237, 235, 234, 233, 232, 231, 230, 229,
       228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217, 216,
       215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203,
       202, 201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191, 190,
       189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 179, 178, 177,
       176, 175, 174, 173, 172, 171, 170, 169, 168, 167, 166, 165, 164,
       163, 162, 161, 160, 159, 158, 157, 156, 155, 154, 153, 15

In [91]:
# Recupera un registro en particular del DataFrame, en este caso, el primer registro.
dfFromCsv.loc[0]

Registros                  10357
Peso                     6138999
Duración                     398
Fecha                 2023-11-13
Ini          2023-11-13 18:25:02
Fin          2023-11-13 19:21:23
Name: 0, dtype: object

In [93]:
# Recupera un grupo de registros del DataFrame, en este caso, el del 2do registro al 5to. (los indicies numericos inician en 0)
dfFromCsv.loc[1:4]

Registros     Peso  Duración       Fecha                  Ini  \
1      11265  6692498       397  2023-07-17  2023-07-17 20:20:01   
2      11265  6692498       395  2023-07-17  2023-07-17 20:19:02   
3      11946  5405356       395  2023-12-05  2023-12-05 16:05:01   
4      11946  5405356       392  2023-12-05  2023-12-05 16:05:01   

                   Fin  
1  2023-07-17 21:02:39  
2  2023-07-17 21:10:36  
3  2023-12-05 17:24:37  
4  2023-12-05 17:20:34